---
title: "index.Rmd"
author: "Daniella Tsing, Brandon Nguyen, Eugene Kim, Roberto Raftery"
date: '2022-05-12'
output: html_document
---
### **Introduction**
The data set contains information about the indicators of diabetes for 253,680 survey respondents. Indicators include factors such as cholesterol levels, BMI, and income. The data was collected by the Centers for Disease Control and Prevention (CDC) via a telephone survey called the Behavioral Risk Factor Surveillance System (BRFSS) in 2015. The data set contains 22 columns and 253,680 rows. From this dataset, we are able to determine factors that influence an individual's likelihood of becoming diagnosed with diabetes. These factors include social and behavioral factors along with health factors, so we will also be able to analyze the intersection between an individual's social environment and an individual's physical well-being. The social factors provided in this dataset include age, income, and sex. From these categories, we may discern whether men or women are more likely to become diabetics, how income factors into healthcare, and what age group has the highest number of diabetics. By analyzing social factors, we can ask further questions to explore the cause and effect relationships created by these factors. Moreover, the dataset contains information about an individual's behavioral, such as smoking and eating habits, and how it predisposes them to diabetes. Along with health factors such as cholesterol levels, these social and behavioral patterns will give us a more well-rounded understanding of the contributors to diabetes.

### **Summary**
```{r include = FALSE}
source("summary.R", local = knitr::knit_global())
```
`r diabetes_summary`

The summary function calculates several values on the diabetes dataset, such as the highs and averages within the data. The first value of summary (`r diabetes_summary$avg_bmi_diabetes`) includes the average BMI of those who are diabetic, which allows us to look at how diabetes impacts a patient's BMI. The second (`r diabetes_summary$low_income_trend`) and third values (`r diabetes_summary$high_income_trend`) of summary includes the ratio of those in low income and high income who have diabetes, allowing us to see the trend of if having diabetes is correlated to income, in which it is. The fourth value of summary (`r diabetes_summary$age_trend`) consists of the age with the highest counts of diabetic cases, examining what age is most likely to have diabetes based on the highest amount of cases. The last value of summary (`r diabetes_summary$heart_disease_with_diabetes`) displays the likelihood for someone with diabetes to have heart disease, which is quantified from filtering diabetes cases, and analyzing the cases where patients do have both diabetes and heart disease, or simply diabetes.

### **Aggregated Table**
Why did you add the table? What does it reveal?

### **Charts**
Describe the purpose of including the chart. Describe any notable observations and 
insights from the chart.
